name: Automatic lockfile update.
on:
  schedule:
    - cron: '39 0 * * 6'
  workflow_dispatch:

jobs:
  update-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: update flake lockfile
        run: nix flake update
        
      - name: clone bevy repo
        run: nix run nixpkgs#git clone https://github.com/bevyengine/bevy.git bevy -- -b release-0.18.1

      - name: test by building breakout
        working-directory: bevy
        run: |
          nix run ..#rust-toolchain build -- --example breakout
          nix run ..#rust-toolchain clean
        
      - name: push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add ./flake.lock
          git commit -m "Automatic lockfile update." | true
          git push origin main
