name: Automatic lockfile update.
on:
  schedule:
    - cron: '39 0 * * 6'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: update flake lockfile
        run: nix flake update
        
      - name: install git and cargo
        run: |
          nix profile add "nixpkgs#git"
          nix profile add ".#rust-toolchain"

      - name: clone bevy repo
        run: git clone https://github.com/bevyengine/bevy.git bevy -b release-0.18.1

      - name: test by building breakout
        working-directory: bevy
        run: |
          cargo build
          cargo build --example breakout --target x86_64-unknown-linux-gnu
          cargo build --example breakout --target aarch64-unknown-linux-gnu
          cargo build --example breakout --target x86_64-pc-windows-msvc
          cargo build --example breakout --target aarch64-pc-windows-msvc
          cargo build --example breakout --target wasm32-unknown-unknown
        
      - name: push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add ./flake.lock
          git commit -m "Automatic lockfile update." | true
          git push origin main
